"""Gemini 2.5 Flash API Client.

A lightweight, secure wrapper around the official google-genai SDK.
Handles communication, system instruction injection, and streaming responses
for the RFC Atlas RAG synthesis layer.
"""

import logging
import os
from collections.abc import Generator

from google import genai
from google.genai import types

logger = logging.getLogger(__name__)


class GeminiClient:
    """Client for communicating with the Google Gemini 2.5 Flash model."""

    _MODEL_ID = "gemini-2.5-flash"

    def __init__(self) -> None:
        """Initializes the Gemini client.

        Relies on the GEMINI_API_KEY environment variable. Will fail securely
        if the key is not present in the environment.

        Raises:
            ValueError: If the API key is missing.
        """
        if not os.environ.get("GEMINI_API_KEY"):
            logger.error("GEMINI_API_KEY environment variable is not set.")
            e = "Missing GEMINI_API_KEY. Please ensure your .env file is configured."
            raise ValueError(e)

        self._client = genai.Client()

    @staticmethod
    def _build_config(system_instruction: str) -> types.GenerateContentConfig:
        """Constructs the generation configuration with strict RAG parameters.

        Args:
            system_instruction (str): The strict system prompt constraints.

        Returns:
            types.GenerateContentConfig: The configured SDK parameters.
        """
        return types.GenerateContentConfig(
            system_instruction=system_instruction,
            temperature=0.2,
            top_p=0.8,
        )

    def generate_response(self, prompt: str, system_instruction: str) -> str:
        """Sends a prompt to Gemini and returns the complete synthesized response.

        Args:
            prompt (str): The combined user query and Markdown context blocks.
            system_instruction (str): The strict system prompt constraints.

        Returns:
            str: The synthesized, citation-backed response from the LLM.
        """
        logger.info("Sending RAG payload to %s...", self._MODEL_ID)

        response = self._client.models.generate_content(  # pyright: ignore[reportUnknownMemberType]
            model=self._MODEL_ID,
            contents=prompt,
            config=self._build_config(system_instruction),
        )

        return str(response.text)

    def generate_stream(
        self, prompt: str, system_instruction: str
    ) -> Generator[str, None, None]:
        """Streams the response back from Gemini for real-time UI/CLI feedback.

        Args:
            prompt (str): The combined user query and Markdown context blocks.
            system_instruction (str): The strict system prompt constraints.

        Yields:
            str: Sequential text chunks as they are generated by the model.
        """
        logger.info("Initiating streaming connection to %s...", self._MODEL_ID)

        response_stream = self._client.models.generate_content_stream(  # pyright: ignore[reportUnknownMemberType]
            model=self._MODEL_ID,
            contents=prompt,
            config=self._build_config(system_instruction),
        )

        for chunk in response_stream:
            if chunk.text:
                yield chunk.text
