"""Gemini 2.5 Flash API Client.

A lightweight, secure wrapper around the official google-genai SDK.
Handles communication, system instruction injection, and streaming responses
for the RFC Atlas RAG synthesis layer.
"""

import logging
from collections.abc import Generator

from google import genai
from google.genai import types
from google.genai.errors import APIError

from rfc_atlas.utils.exceptions import SynthesisError

logger = logging.getLogger(__name__)


class GeminiClient:
    """Client for communicating with the Google Gemini 2.5 Flash model."""

    _MODEL_ID = "gemini-2.5-flash"

    def __init__(self) -> None:
        """Initializes the Gemini client, delegating auth to the official SDK."""
        self._client = genai.Client()

    @staticmethod
    def _build_config(
        system_instruction: str, temperature: float, top_p: float
    ) -> types.GenerateContentConfig:
        """Constructs the generation configuration with strict RAG parameters.

        Args:
            system_instruction (str): The strict system prompt constraints.
            temperature (float): The sampling temperature.
            top_p (float): Nucleus sampling threshold.

        Returns:
            types.GenerateContentConfig: The configured SDK parameters.
        """
        return types.GenerateContentConfig(
            system_instruction=system_instruction,
            temperature=temperature,
            top_p=top_p,
            safety_settings=[
                types.SafetySetting(
                    category=types.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
                    threshold=types.HarmBlockThreshold.BLOCK_NONE,
                ),
                types.SafetySetting(
                    category=types.HarmCategory.HARM_CATEGORY_HATE_SPEECH,
                    threshold=types.HarmBlockThreshold.BLOCK_NONE,
                ),
                types.SafetySetting(
                    category=types.HarmCategory.HARM_CATEGORY_HARASSMENT,
                    threshold=types.HarmBlockThreshold.BLOCK_NONE,
                ),
                types.SafetySetting(
                    category=types.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
                    threshold=types.HarmBlockThreshold.BLOCK_NONE,
                ),
            ],
        )

    def generate_response(
        self,
        prompt: str,
        system_instruction: str,
        temperature: float = 0.2,
        top_p: float = 0.8,
    ) -> str:
        """Sends a prompt to Gemini and returns the complete synthesized response.

        Args:
            prompt (str): The combined user query and Markdown context blocks.
            system_instruction (str): The strict system prompt constraints.
            temperature (float): Controls generation randomness. Default is 0.2.
            top_p (float): Controls nucleus sampling. Default is 0.8.

        Returns:
            str: The synthesized, citation-backed response from the LLM.

        Raises:
            SynthesisError: If the Gemini API call fails.
        """
        logger.info("Sending RAG payload to %s...", self._MODEL_ID)

        try:
            response = self._client.models.generate_content(  # pyright: ignore[reportUnknownMemberType]
                model=self._MODEL_ID,
                contents=prompt,
                config=self._build_config(system_instruction, temperature, top_p),
            )
        except APIError as e:
            logger.exception("Gemini API Error")
            raise SynthesisError(e) from e

        if response.candidates and response.candidates[0].finish_reason != "STOP":
            reason = response.candidates[0].finish_reason
            return f"⚠️ Generation halted prematurely. Finish reason: {reason}"

        if not response.text:
            return (
                "⚠️ The model returned an empty response. "
                "This may be due to safety filters or a generation error."
            )

        return str(response.text)

    def generate_stream(
        self,
        prompt: str,
        system_instruction: str,
        temperature: float = 0.2,
        top_p: float = 0.8,
    ) -> Generator[str, None, None]:
        """Streams the response back from Gemini for real-time UI/CLI feedback.

        Args:
            prompt (str): The combined user query and Markdown context blocks.
            system_instruction (str): The strict system prompt constraints.
            temperature (float): Controls generation randomness. Default is 0.2.
            top_p (float): Controls nucleus sampling. Default is 0.8.

        Yields:
            str: Sequential text chunks as they are generated by the model.

        Raises:
            SynthesisError: If the Gemini API call fails during streaming.
        """
        logger.info("Initiating streaming connection to %s...", self._MODEL_ID)

        try:
            response_stream = self._client.models.generate_content_stream(  # pyright: ignore[reportUnknownMemberType]
                model=self._MODEL_ID,
                contents=prompt,
                config=self._build_config(system_instruction, temperature, top_p),
            )

            for chunk in response_stream:
                if chunk.text:
                    yield chunk.text
        except APIError as e:
            logger.exception("Gemini API Error during streaming")
            raise SynthesisError(e) from e
