"""Master Orchestrator for the Synthesis Layer.

Provides the top-level API boundary for the RFC Atlas backend. Connects the
Retrieval Engine (LanceDB/Reranker) to the Synthesis Engine (Gemini) to execute
the complete end-to-end Retrieval-Augmented Generation (RAG) pipeline.
"""

import logging
from collections.abc import Generator
from pathlib import Path

from rfc_atlas.retrieval.orchestrator import RetrievalOrchestrator
from rfc_atlas.synthesis.gemini_client import GeminiClient
from rfc_atlas.synthesis.prompts import SYSTEM_INSTRUCTION, build_rag_prompt

logger = logging.getLogger(__name__)


class SynthesisOrchestrator:
    """Coordinates the end-to-end RAG pipeline from query to LLM synthesis."""

    def __init__(self, db_path: Path | str | None = None) -> None:
        """Initializes the full backend pipeline infrastructure.

        Args:
            db_path (Path | str | None): Optional path to a specific LanceDB instance.
                Passed down to the RetrievalOrchestrator.
        """
        logger.info("Booting Retrieval Engine...")
        self.retrieval_engine = RetrievalOrchestrator(db_path=db_path)

        logger.info("Booting Gemini Synthesis Engine...")
        self.llm_client = GeminiClient()

    def query(self, query_text: str, top_k: int = 10) -> str:
        """Executes a complete RAG query, returning the final synthesized answer.

        Args:
            query_text (str): The natural language question from the user.
            top_k (int): Number of context chunks to retrieve and inject.

        Returns:
            str: The final, citation-backed Markdown response from Gemini.
        """
        logger.info("Executing End-to-End RAG Pipeline for query: '%s'", query_text)

        context_markdown = self.retrieval_engine.retrieve_context(
            query=query_text, top_k=top_k
        )
        rag_payload = build_rag_prompt(
            query=query_text, context_blocks=context_markdown
        )

        return self.llm_client.generate_response(
            prompt=rag_payload, system_instruction=SYSTEM_INSTRUCTION
        )

    def stream_query(
        self, query_text: str, top_k: int = 10
    ) -> Generator[str, None, None]:
        """Executes a complete RAG query, streaming the LLM response back in chunks.

        Ideal for CLI or WebSocket UI implementations to reduce perceived latency.

        Args:
            query_text (str): The natural language question from the user.
            top_k (int): Number of context chunks to retrieve and inject.

        Yields:
            str: Sequential text fragments generated by Gemini.
        """
        logger.info("Executing Streaming RAG Pipeline for query: '%s'", query_text)

        context_markdown = self.retrieval_engine.retrieve_context(
            query=query_text, top_k=top_k
        )
        rag_payload = build_rag_prompt(
            query=query_text, context_blocks=context_markdown
        )

        yield from self.llm_client.generate_stream(
            prompt=rag_payload, system_instruction=SYSTEM_INSTRUCTION
        )
